USE FootballLeague;
GO
-- Drop tables
DROP TABLE IF EXISTS dbo.AU_TB_UserRole;
DROP TABLE IF EXISTS dbo.AU_LG_RefreshToken;
DROP TABLE IF EXISTS dbo.AU_TB_User;
DROP TABLE IF EXISTS dbo.AU_TB_Role;

-- Create tables
CREATE TABLE dbo.AU_TB_User(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	FirstName NVARCHAR(40) NOT NULL,
	LastName NVARCHAR(40) NULL,
	Password NVARCHAR(MAX) NOT NULL,
	Email NVARCHAR(40) NOT NULL,
	CreateDate DATETIME NOT NULL,
	UpdateDate DATETIME NULL,
	PhoneNumber NVARCHAR(15) NULL
);
GO


CREATE TABLE dbo.AU_TB_Role(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(20) NOT NULL,
	CreateDate DATETIME NOT NULL,
	UpdateDate DATETIME NULL,
);

GO
CREATE TABLE dbo.AU_TB_UserRole(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	UserId INT NOT NULL,
	RoleId INT NOT NULL
);
GO

CREATE TABLE dbo.AU_LG_RefreshToken(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Token NVARCHAR(MAX) NOT NULL,
	JwtId INT NOT NULL,
	CreateDate DATETIME NOT NULL,
	ExpireDate DATETIME NOT NULL,
	Used BIT NOT NULL,
	UserId INT NOT NULL
);

-- Foreign keys

ALTER TABLE dbo.AU_TB_UserRole
WITH CHECK ADD CONSTRAINT FK_User_UserRole
FOREIGN KEY (UserId) REFERENCES dbo.AU_TB_User(Id);
GO

ALTER TABLE dbo.AU_TB_UserRole
WITH CHECK ADD CONSTRAINT FK_Role_UserRole
FOREIGN KEY (RoleId) REFERENCES dbo.AU_TB_Role(Id);
GO

ALTER TABLE dbo.AU_LG_RefreshToken
WITH CHECK ADD CONSTRAINT FK_User_RefreshToken
FOREIGN KEY (UserId) REFERENCES dbo.AU_TB_User(Id);
GO



-- Create indexes

CREATE NONCLUSTERED INDEX Email ON dbo.AU_TB_User (Email ASC);

CREATE NONCLUSTERED INDEX UserId ON dbo.AU_TB_UserRole (UserId ASC);
CREATE NONCLUSTERED INDEX RoleId ON dbo.AU_TB_UserRole (RoleId ASC);

CREATE NONCLUSTERED INDEX UserId ON dbo.AU_LG_RefreshToken (UserId ASC);